version: '3'

include:
  - docker-compose.yml

services:
  # ADDONS:
  jpo_bsm_query:
    build:
      context: ./services
      dockerfile: Dockerfile.bsm_query
    image: bsm_query:latest
    restart: always

    env_file:
      - ./services/addons/images/bsm_query/.env
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  jpo_count_metric:
    build:
      context: ./services
      dockerfile: Dockerfile.count_metric
    image: count_metric:latest
    restart: always

    env_file:
      - ./services/addons/images/count_metric/.env
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  jpo_rsu_ping_fetch:
    build:
      context: ./services
      dockerfile: Dockerfile.rsu_ping_fetch
    image: rsu_ping_fetch:latest
    restart: always

    depends_on:
      - cvmanager_postgres
    env_file:
      - ./services/addons/images/rsu_ping/.env
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  jpo_iss_health_check:
    build:
      context: ./services
      dockerfile: Dockerfile.iss_health_check
    image: iss_health_check:latest
    restart: always

    depends_on:
      - cvmanager_postgres
    env_file:
      - ./services/addons/images/iss_health_check/.env
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  firmware_manager:
    build:
      context: services
      dockerfile: Dockerfile.firmware_manager
    image: jpo_firmware_manager:latest
    restart: always

    ports:
      - '8089:8080'
    environment:
      PG_DB_HOST: ${PG_DB_HOST}
      PG_DB_NAME: postgres
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PASS: ${PG_DB_PASS}

      BLOB_STORAGE_PROVIDER: ${BLOB_STORAGE_PROVIDER}
      BLOB_STORAGE_BUCKET: ${BLOB_STORAGE_BUCKET}

      GCP_PROJECT: ${GCP_PROJECT}
      GOOGLE_APPLICATION_CREDENTIALS: '/google/gcp_credentials.json'

      LOGGING_LEVEL: ${API_LOGGING_LEVEL}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google/gcp_credentials.json
      - ${HOST_BLOB_STORAGE_DIRECTORY}:/mnt/blob_storage
    logging:
      options:
        max-size: '10m'
        max-file: '5'