FROM python:3.12.2-alpine3.18

# Prepare the SNMP functionality for the image
RUN apk update && apk add net-snmp && apk add net-snmp-tools && apk add ca-certificates
COPY resources/mibs/* /usr/share/snmp/mibs/

COPY resources/ca/ca.crt /usr/local/share/ca-certificates/ca.crt
RUN update-ca-certificates

WORKDIR /home

COPY addons/images/rsu_status_check/crontab .
COPY addons/images/rsu_status_check/requirements.txt .
COPY addons/images/rsu_status_check/*.py .
COPY common/ ./common/

RUN pip3 install -r requirements.txt

# fix the line endings from windows
RUN dos2unix /home/crontab && crontab /home/crontab

CMD ["crond", "-f"]
