# Pipeline for building web app

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - 'webapp/*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'webapp'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Publish the artifacts directory for consumption in publish pipeline
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'jpo-cvmanager-webapp'
      publishLocation: 'Container'
